pilote_particles_homepage:
    path:     /particles/
    defaults: { _controller: PiloteParticlesBundle:Default:index }
    
pilote_particles_scansPage:
    path:     /particles/scans/
    defaults: { _controller: PiloteParticlesBundle:Scan:scans }
    
pilote_particles_mapSetupPage:
    path:     /particles/setup-map/
    defaults: { _controller: PiloteParticlesBundle:Scan:mapSetup }
    
pilote_particles_scanResultPage:
    path:     /particles/scanned/
    defaults: { _controller: PiloteParticlesBundle:Scan:doScan }
