pilote_doe:
    resource: "@PiloteDoeBundle/Resources/config/routing.yml"
    prefix:   /

pilote_issues:
    resource: "@PiloteIssuesBundle/Resources/config/routing.yml"
    prefix:   /

pilote_projects:
    resource: "@PiloteProjectsBundle/Resources/config/routing.yml"
    prefix:   /

pilote_user:
    resource: "@PiloteUserBundle/Resources/config/routing.yml"
    prefix:   /

pilote_core:
    resource: "@PiloteCoreBundle/Resources/config/routing.yml"
    prefix:   /
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /
    
login:
    pattern:   /login
    defaults:  { _controller: PiloteUserBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout