# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
            FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_EBUSINESS: [ROLE_USER]
        ROLE_MARKETING: [ROLE_USER]
        ROLE_PENPUSHER: [ROLE_USER]
        ROLE_EXECUTIVE: [ROLE_USER]
        ROLE_STUDIO: [ROLE_USER]
        ROLE_COMMUNICATION: [ROLE_USER]
        ROLE_LOGISTIC: [ROLE_USER]
        ROLE_BUSINESS: [ROLE_USER]
        ROLE_PROJET: [ROLE_USER]
        ROLE_DEV: [ROLE_USER, ROLE_PROJET]
        ROLE_QA: [ROLE_USER, ROLE_DEV, ROLE_PROJET, ROLE_BUSINESS]
        ROLE_SWITCHBOARD: [ROLE_USER, ROLE_DEV, ROLE_QA, ROLE_PROJET, ROLE_BUSINESS, ROLE_LOGISTIC, ROLE_COMMUNICATION, ROLE_STUDIO, ROLE_EXECUTIVE, ROLE_PENPUSHER, ROLE_MARKETING, ROLE_EBUSINESS]
        ROLE_POWA: [ROLE_USER, ROLE_SWITCHBOARD]
        ROLE_PM: [ROLE_USER, ROLE_POWA]
        ROLE_PO: [ROLE_USER, ROLE_PM]
        ROLE_ADMIN: [ROLE_USER, ROLE_PO]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        main_login:
            pattern: ^/login$
            anonymous: true
            #logout: true
            
        main:
            pattern: ^/
            anonymous: false
            
            form_login:
                provider:  fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                login_path: /login
                check_path: /login_check
            logout:
                path:   /logout
                target: /
                
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: ROLE_ADMIN }
        - { path: ^/admin/, role: IS_AUTHENTICATED_ANONYMOUSLY}
