# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
            FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_PO, ROLE_PM, ROLE_POWA, ROLE_SWITCHBOARD, ROLE_DEV, ROLE_QA, ROLE_PROJET, ROLE_BUSINESS, ROLE_LOGISTIC, ROLE_COMMUNICATION, ROLE_STUDIO, ROLE_EXECUTIVE, ROLE_PENPUSHER, ROLE_MARKETING, ROLE_EBUSINESS]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        main_login:
            pattern: ^/login$
            anonymous: true
            #logout: true
            
        main:
            pattern: ^/
            anonymous: true
            
            form_login:
                provider:  fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                login_path: login
                check_path: login_check
            logout:
                path:   logout
                target: /
                
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: ROLE_ADMIN }
        - { path: ^/admin/, role: IS_AUTHENTICATED_ANONYMOUSLY}
