<?php

namespace Pilote\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserInfosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserInfosRepository extends EntityRepository
{
}
